### ISSUE TITLE
Training my data error

### ISSUE THREAD

**Issue by S130111** [zhiminzhang0830/FCENet_Paddle#3]
Traceback (most recent call last):
  File "/home/software/anaconda2019/envs/FCENet/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 329, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/home/software/anaconda2019/envs/FCENet/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "/home/root1/SHI/FCENet_Paddle/ppocr/data/simple_dataset.py", line 120, in __getitem__
    outs = transform(data, self.ops)
  File "/home/root1/SHI/FCENet_Paddle/ppocr/data/imaug/__init__.py", line 44, in transform
    data = op(data)
  File "/home/root1/SHI/FCENet_Paddle/ppocr/data/imaug/fce_targets.py", line 1312, in __call__
    results = self.generate_targets(results)
  File "/home/root1/SHI/FCENet_Paddle/ppocr/data/imaug/fce_targets.py", line 1297, in generate_targets
    polygon_masks_ignore)
  File "/home/root1/SHI/FCENet_Paddle/ppocr/data/imaug/fce_targets.py", line 1252, in generate_level_targets
    level_img_size, lv_text_polys[ind])
  File "/home/root1/SHI/FCENet_Paddle/ppocr/data/imaug/fce_targets.py", line 1126, in generate_fourier_maps
    fourier_coeff = self.cal_fourier_signature(polygon[0], k)
  File "/home/root1/SHI/FCENet_Paddle/ppocr/data/imaug/fce_targets.py", line 1085, in cal_fourier_signature
    resampled_polygon = self.normalize_polygon(resampled_polygon)
  File "/home/root1/SHI/FCENet_Paddle/ppocr/data/imaug/fce_targets.py", line 1032, in normalize_polygon
    x = np.abs(temp_polygon[:, 0])
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by zhiminzhang0830** [comment]
You may want to check your data for anomalies, such as the area is zero

**Comment by S130111** [comment]
> 您可能需要检查数据是否存在异常，例如面积为零

你好，数据有什么要求吗 我的格式按您的数据格式制作，但还是不对，查看数据也没有异常，又出现下面的错误
  File "/home/root1/SHI/FCENet_Paddle/ppocr/data/simple_dataset.py", line 119, in __getitem__
    outs = transform(data, self.ops)
  File "/home/root1/SHI/FCENet_Paddle/ppocr/data/imaug/__init__.py", line 44, in transform
    data = op(data)
  File "/home/root1/SHI/FCENet_Paddle/ppocr/data/imaug/fce_targets.py", line 1324, in __call__
    results = self.generate_targets(results)
  File "/home/root1/SHI/FCENet_Paddle/ppocr/data/imaug/fce_targets.py", line 1309, in generate_targets
    polygon_masks_ignore)
  File "/home/root1/SHI/FCENet_Paddle/ppocr/data/imaug/fce_targets.py", line 1254, in generate_level_targets
    level_img_size, lv_text_polys[ind])[None]
  File "/home/root1/SHI/FCENet_Paddle/ppocr/data/imaug/fce_targets.py", line 953, in generate_center_region_mask
    top_line, bot_line, self.resample_step)
  File "/home/root1/SHI/FCENet_Paddle/ppocr/data/imaug/fce_targets.py", line 923, in resample_sidelines
    resampled_line1 = self.resample_line(sideline1, resample_point_num)
  File "/home/root1/SHI/FCENet_Paddle/ppocr/data/imaug/fce_targets.py", line 730, in resample_line
    while current_line_len >= length_cumsum[current_edge_ind + 1]:
IndexError: index 14 is out of bounds for axis 0 with size 14
